spring.application.name=rutafit

# MongoDB

spring.application.name=biblioteca-api
spring.data.mongodb.uri=mongodb+srv://AdminBiblioteca:Biblio2026.@biblioteca-cluster.doc0kpd.mongodb.net/biblioteca_db?appName=biblioteca-cluster
spring.data.mongodb.database=biblioteca_db
server.port=8080

# JWT
app.jwt.secret=clave-secreta-rutafit-cambiar-en-produccion
app.jwt.expiration=86400000

# Mail
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=tu-correo@gmail.com
spring.mail.password=tu-contrasena
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
